version: '3.3'

services:

  alertmanager:
    build: .
    image: flaviostutz/alertmanager-webhook
    ports:
      - 9093:9093
    environment:
      - WEBHOOK_URL=http://telegrambot:8080
    volumes:
      - alertmanager:/alertmanager

  telegrambot:
    image: metalmatze/alertmanager-bot:0.3.1
    environment:
      - ALERTMANAGER_URL=http://alertmanager:9093
      - BOLT_PATH=/data/bot.db
      - STORE=bolt
      - LISTEN_ADDR=0.0.0.0:8080
      - TELEGRAM_ADMIN=AAAAA
      - TELEGRAM_TOKEN=BBBBB:KKKKKKKK
    volumes:
      - telegrambot:/data

  unsee:
    image: cloudflare/unsee:v0.8.0
    ports:
      - 8080:8080
    environment:
      - ALERTMANAGER_URIS=default:http://alertmanager:9093

volumes:
  alertmanager:
  telegrambot:
